### ISSUE TITLE
where do the data files come from

### ISSUE THREAD

**Issue by smrgeoinfo** [miguelcleon/River-nutrient-exports-Puerto-Rico-#1]
MIguel-- we're interested in notebooks that can operated with data from the web. Can  the data that your notebooks here work with (files in the data directory) be acquired via URL/GET from some repositor API?

**Comment by miguelcleon** [comment]
Hi @smrgeoinfo I have some notebooks on hydroshare that do that:

This one interacts with an ODM2 SQLite database hosted on Hydroshare using the ODM2PythonAPI and with USGS data accessed through ulmo. 
https://www.hydroshare.org/resource/2fd6d9d2ca16423db921f5c36fcbb073/

These interact with remote postgresql ODM2 databases using the ODM2PythonAPI

https://www.hydroshare.org/resource/a1e35535a8894d6f840e23640ba05143/
https://www.hydroshare.org/resource/c53a388d68654fd3b2c5fc45fb0a520f/

I've also built one I think that can interact with an ODM2 database through WOFpy (water one flow web services).  

So there are a number of possibilities, this particular repo builds on some work another person started and so it starts with some files in a directory.

**Comment by smrgeoinfo** [comment]
Thanks Miguel!
